### ISSUE TITLE
Implementar o Design do Autocomplete

### ISSUE THREAD

**Issue by livingrio-kbl** [livingrio-kbl/br.com.livingrio#22]
Implementar o Design do Autocomplete.

**Comment by livingrio-gcc** [comment]
Dei uma melhorada no autocomplete.

Para cada resultItem do autocomplete defini alguns paddings para dar um espaçamento entre os itens.

Na Div que engloba todo o autocomplete coloquei o position absolute para ficar por cima da barra de menu (flutuando.)
