### ISSUE TITLE
Ir para Rio das Ostras

### ISSUE THREAD

**Issue by livingrio-kbl** [livingrio-kbl/br.com.livingrio#24]
Perder 48hs de desenvolvimento para tomar cervejas na Região dos Lagos.

**Comment by livingrio-gcc** [comment]
Chorou! Lembra dos estagiários! Certeza ideias novas virão!! #xerebecanto

**Comment by livingrio-kbl** [comment]
Já comprei uma grande diversidade de cerveja.
